name: Tests

on:
  push:
    branches-ignore:
      - main

env:
  m2-cache-path: ~/.m2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ env.m2-cache-path }}
          key: cache-key-v1.0.0

      - name: Build
        run: |
          echo "BUILD START"
          mvn clean install -Dmaven.skip.test=true 

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ env.m2-cache-path }}
          key: cache-key-v1.0.0

      - name: Test
        run: |
          echo "TEST START"
          mvn verify
